#!/bin/bash

set -e

echo 'KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0666"' > /etc/udev/rules.d/00-expose-hidraw.rules

echo 'KERNEL=="uhid", SUBSYSTEM=="misc", MODE="0666"' > /etc/udev/rules.d/00-expose-uhid.rules

/bin/udevadm trigger

test ! -e /etc/rc.local || /bin/mv /etc/rc.local{,.backup."$(/bin/date +%Y%m%d%H%M%S)"}

echo '#!/bin/bash
> /dev/uhid
exit 0' > /etc/rc.local

/bin/chmod +x /etc/rc.local

> /dev/uhid
