#!/bin/bash

set -e


#
# I'd like to have 0666 permission for both /dev/uhid and /dev/hidraw*
#

tee /etc/udev/rules.d/00-expose-hidraw.rules > /dev/null <<< 'KERNEL=="hidraw*", SUBSYSTEM=="hidraw", MODE="0666"'
tee /etc/udev/rules.d/00-expose-uhid.rules > /dev/null <<< 'KERNEL=="uhid", SUBSYSTEM=="misc", MODE="0666"'

test ! -e /etc/rc.local || /bin/mv /etc/rc.local /etc/rc.local.backup."$(/bin/date +%Y%m%d%H%M%S)"


tee /etc/rc.local > /dev/null << 'END'
#!/bin/bash
/bin/udevadm trigger
/bin/dd if=/dev/null of=/dev/uhid
exit 0
END
/bin/chmod +x /etc/rc.local


#
# make it work without rebooting
#

/bin/udevadm trigger
/bin/dd if=/dev/null of=/dev/uhid
/bin/chmod 0666 /dev/uhid
